import Image from "next/image";
import type { Project } from "@/data/projects";
import { CaseStudyBackLink, CaseStudyClosingCta } from "./CaseStudyLayout";

const base = "/projects/pillars-pr";
const decisions = [
  ["Specialist Over Generic", "The identity needed to communicate that Pillars understands the legal sector, not simply general marketing."],
  ["Structure as a Brand Device", "The pillar concept became a recognizable graphic system rather than relying only on generic legal symbols."],
  ["Authority Without Feeling Outdated", "Blue, structured layouts, and clear hierarchy established credibility while maintaining a contemporary character."],
  ["One Connected System", "The identity was designed to work consistently across corporate documents, commercial communication, social media, and motion."],
] as const;
const responsibilities = ["Brand Identity", "Logo Design", "Visual Direction", "Corporate Design", "Social Media", "Logo Motion", "Motion & Video"] as const;
const deliverables = ["Logo System", "Visual Identity", "Company Profile", "Corporate Documents", "Pricing Presentation", "Social Media Designs", "Logo Animation", "Motion & Video"] as const;

function Heading({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) {
  return <div><p className="font-display text-sm uppercase tracking-[0.22em] text-ink-faint md:text-base">{eyebrow}</p><h2 className="mt-4 max-w-4xl text-3xl font-semibold leading-tight text-ink md:text-5xl">{children}</h2></div>;
}

function PreviewVisual({ label, ratio = "landscape", children }: { label: string; ratio?: "landscape" | "portrait" | "square" | "wide"; children?: React.ReactNode }) {
  const ratios = { landscape: "aspect-[3/2]", portrait: "aspect-[4/5]", square: "aspect-square", wide: "aspect-[2/1]" } as const;
  return <figure className="min-w-0"><div role="img" aria-label={`${label}. Unpublished preview; approved artwork pending.`} className={`relative grid min-w-0 place-items-center overflow-hidden rounded-xl border border-[#2469d8]/25 bg-[#071a33] p-6 text-white ${ratios[ratio]}`}>
    <div aria-hidden="true" className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(117,171,255,.35) 1px, transparent 1px), linear-gradient(90deg, rgba(117,171,255,.35) 1px, transparent 1px)", backgroundSize: "40px 40px" }} />
    <div aria-hidden="true" className="absolute inset-y-0 left-[12%] w-[7%] bg-[#2469d8]/70" /><div aria-hidden="true" className="absolute inset-y-[16%] left-[23%] w-[7%] border-x border-[#75abff]/50" />
    <div className="relative z-10 w-full max-w-xl">{children ?? <><p className="text-xs uppercase tracking-[0.24em] text-[#a9c9ff]">Approved artwork pending</p><p className="mt-3 max-w-md text-xl font-medium leading-8 text-white md:text-2xl">{label}</p></>}</div>
  </div></figure>;
}

function PendingSocialGrid() {
  return <div className="mt-10 overflow-hidden rounded-[1.5rem] border border-edge bg-surface-card/45 shadow-2xl shadow-black/10">
    <div className="flex items-center gap-4 border-b border-edge px-5 py-5 sm:px-8"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full border-2 border-[#2469d8] bg-[#071a33] text-xs font-semibold text-white">PPR</div><div className="min-w-0 flex-1"><h3 className="text-base font-semibold text-ink sm:text-lg">Pillars PR</h3><p className="text-sm leading-6 text-ink-soft">Legal marketing &amp; public relations · Abu Dhabi</p></div></div>
    <div className="grid grid-cols-2 gap-[2px] bg-edge sm:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <div key={index} className="aspect-[3/4] bg-[#071a33] p-4"><div className="grid h-full place-items-center border border-[#75abff]/25 text-center text-xs uppercase tracking-[0.16em] text-[#a9c9ff]">Approved social design pending</div></div>)}</div>
    <p className="px-5 py-4 text-center text-sm text-ink-soft">The shared Instagram viewer will be enabled when approved Pillars social assets are supplied.</p>
  </div>;
}

export default function PillarsPrCaseStudy({ project }: { project: Project }) {
  return <main id="main-content" tabIndex={-1} className="flex-1 pt-32 md:pt-40"><article className="mx-auto max-w-6xl px-6">
    <CaseStudyBackLink />
    <div className="relative mt-6 aspect-[4/5] overflow-hidden bg-[#071a33] sm:aspect-[1200/630]"><Image src={`${base}/pillars-pr-og-preview.svg`} alt="Unpublished Pillars PR identity preview using a structured blue pillar motif and the tagline Building Legal Excellence." fill priority sizes="(min-width: 1152px) 1152px, 100vw" className="object-cover" /></div>
    <header className="py-14 md:py-20">
      <p className="font-display text-sm uppercase tracking-[0.22em] text-ink-faint md:text-base">{project.subtitle}</p><h1 className="mt-5 max-w-5xl text-4xl font-semibold leading-tight text-ink md:text-7xl">Pillars PR</h1>
      <div className="mt-8 max-w-3xl space-y-3 text-lg leading-8 text-ink-soft md:text-xl md:leading-9"><p>Pillars PR is an Abu Dhabi-based marketing and public relations company specializing in communication for the legal sector across the MENA region.</p><p>I developed a connected visual identity and communication system spanning the logo, corporate documents, commercial communication, social media, logo motion, and video.</p></div>
      <dl className="mt-10 grid gap-6 border-t border-edge pt-7 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase tracking-[0.16em] text-ink-faint">Market</dt><dd className="mt-2 text-sm leading-6 text-ink">UAE and wider MENA region</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-ink-faint">Location</dt><dd className="mt-2 text-sm leading-6 text-ink">Abu Dhabi, UAE</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-ink-faint">Role</dt><dd className="mt-2 text-sm leading-6 text-ink">Brand &amp; Digital Designer<br />Graphic &amp; Multimedia Designer</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-ink-faint">Industry</dt><dd className="mt-2 text-sm leading-6 text-ink">Legal Marketing &amp; Public Relations</dd></div></dl>
      <div className="mt-7"><p className="text-xs uppercase tracking-[0.16em] text-ink-faint">Scope</p><ul className="mt-3 flex flex-wrap gap-2">{["Brand Identity", "Corporate Design", "Social Media", "Motion & Video"].map((item) => <li key={item} className="rounded-full border border-edge px-3.5 py-2 text-xs text-ink-soft">{item}</li>)}</ul></div>
    </header>

    <section id="overview" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="01 / Overview">One Connected Communication System</Heading><div className="mt-10 grid gap-4 sm:grid-cols-2"><PreviewVisual label="Pillars PR logo and monogram" ratio="wide" /><PreviewVisual label="Company-profile design" ratio="wide" /><PreviewVisual label="Social-media system" ratio="wide" /><PreviewVisual label="Logo motion and video" ratio="wide" /></div></section>
    <section id="context" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="02 / Context">Project Context</Heading><div className="mt-10 grid gap-10 md:grid-cols-2 md:gap-16"><div><h3 className="text-lg font-semibold text-ink">Challenge</h3><p className="mt-4 leading-8 text-ink-soft">Pillars PR needed to establish credibility within the legal sector without feeling outdated or overly institutional, while also communicating the modern marketing and public-relations capabilities behind the company.</p></div><div><h3 className="text-lg font-semibold text-ink">Approach</h3><p className="mt-4 leading-8 text-ink-soft">I built a structured visual identity that connected legal authority with contemporary professional communication and extended the same system across corporate documents, commercial material, social media, and motion.</p></div></div><p className="mt-9 text-sm text-ink-faint">Legal credibility · Modern communication · Clear structure · Consistent execution</p></section>
    <section id="brand-idea" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="03 / Positioning">Legal Expertise.<br />Modern Communication.</Heading><div className="mt-10 grid gap-8 md:grid-cols-2 md:gap-16"><p className="text-lg leading-8 text-ink-soft">Pillars PR was positioned as a specialist bridge between the legal sector and modern marketing and public relations.</p><blockquote className="border-l-2 border-[#2469d8] pl-6 text-2xl font-semibold leading-9 text-ink">Building Legal Excellence</blockquote></div></section>
    <section id="identity" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="04 / Identity">Logo &amp; Identity</Heading><div className="mt-10 space-y-5"><PreviewVisual label="Final Pillars PR logo" ratio="wide" /><div className="grid gap-5 sm:grid-cols-2"><PreviewVisual label="PPR monogram" ratio="square" /><PreviewVisual label="Existing logo lockups" ratio="square" /></div></div><p className="mt-8 max-w-3xl text-lg leading-8 text-ink-soft">The PPR monogram integrates classical pillar forms into the identity, connecting the brand with structure, authority, stability, and professional credibility.</p></section>
    <section id="brand-system" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="05 / System">Brand System</Heading><div className="mt-12 grid gap-12 md:grid-cols-2"><div><h3 className="text-xl font-semibold text-ink">Color</h3><p className="mt-4 leading-8 text-ink-soft">The final verified palette will be presented from approved source files. No color values are inferred from preview artwork.</p><PreviewVisual label="Verified Pillars PR color system" ratio="wide" /></div><div><h3 className="text-xl font-semibold text-ink">Typography</h3><p className="mt-4 leading-8 text-ink-soft">The authentic typography specimen will be added when the brand files and display rights are available.</p><PreviewVisual label="Pillars PR typography system" ratio="wide" /></div></div></section>
    <section id="graphic-language" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="06 / Language">Supporting Graphic Language</Heading><p className="mt-7 max-w-3xl text-lg leading-8 text-ink-soft">Pillar geometry, repeated structural forms, blue-led compositions, and professional editorial hierarchy connect the supporting system to the identity.</p><div className="mt-10"><PreviewVisual label="Pillar-based pattern and supporting graphic system" ratio="wide" /></div></section>
    <section id="corporate" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="07 / Corporate">Corporate Communication</Heading><p className="mt-7 max-w-3xl text-lg leading-8 text-ink-soft">The identity was extended into long-form corporate communication, creating a consistent system for presenting the company, its positioning, services, and capabilities.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><PreviewVisual label="Company-profile cover and introduction" ratio="portrait" /><PreviewVisual label="Company-profile mission, vision, services, and Why Us spreads" ratio="portrait" /></div></section>
    <section id="commercial" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="08 / Commercial">Commercial Communication</Heading><p className="mt-7 max-w-3xl text-lg leading-8 text-ink-soft">A consistent document system organized package structure, service hierarchy, and commercial information without making historical prices the focus.</p><div className="mt-10 grid gap-5 sm:grid-cols-3"><PreviewVisual label="Rising package presentation" ratio="portrait" /><PreviewVisual label="Expert package presentation" ratio="portrait" /><PreviewVisual label="Premium package presentation" ratio="portrait" /></div></section>
    <section id="social" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="09 / Social">Social Media System</Heading><p className="mt-7 max-w-3xl text-lg leading-8 text-ink-soft">The identity was extended into a repeatable social-media system designed to communicate legal, professional, educational, and brand-focused content consistently.</p><PendingSocialGrid /></section>
    <section id="motion" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="10 / Motion">Motion &amp; Video</Heading><p className="mt-7 max-w-3xl text-lg leading-8 text-ink-soft">Logo animation and selected motion work extended the identity into time-based communication while preserving the same structured visual character.</p><div className="mt-10 grid gap-5 md:grid-cols-2"><PreviewVisual label="Pillars PR logo animation" /><PreviewVisual label="Selected motion and video work" /></div></section>
    <section id="decisions" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="11 / Rationale">Key Design Decisions</Heading><div className="mt-10 grid gap-x-12 gap-y-9 sm:grid-cols-2">{decisions.map(([title, description], index) => <article key={title} className="border-t border-edge pt-5"><p className="font-display text-sm text-ink-faint">0{index + 1}</p><h3 className="mt-3 text-lg font-semibold text-ink">{title}</h3><p className="mt-2 text-sm leading-7 text-ink-soft">{description}</p></article>)}</div></section>
    <section id="outcome" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="12 / Result">Outcome</Heading><div className="mt-8 max-w-4xl space-y-4 text-lg leading-8 text-ink-soft"><p>The result was a connected identity and communication system that gave Pillars PR a consistent presence across corporate documents, commercial material, social media, and motion.</p><p>The visual system supported the company&apos;s specialist legal-market positioning while remaining flexible across different formats and audiences throughout the region.</p></div></section>
    <section id="scope" className="border-t border-edge py-16 md:py-24"><Heading eyebrow="13 / Contribution">Project Scope</Heading><div className="mt-10 grid gap-10 md:grid-cols-3 md:gap-8"><div><h3 className="text-xs uppercase tracking-[0.16em] text-ink-faint">Role</h3><p className="mt-5 leading-8 text-ink">Brand &amp; Digital Designer<br />Graphic &amp; Multimedia Designer</p></div><div><h3 className="text-xs uppercase tracking-[0.16em] text-ink-faint">Responsibilities</h3><ul className="mt-5 space-y-2 text-sm leading-6 text-ink-soft">{responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3 className="text-xs uppercase tracking-[0.16em] text-ink-faint">Deliverables</h3><ul className="mt-5 space-y-2 text-sm leading-6 text-ink-soft">{deliverables.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>
    <CaseStudyClosingCta title="Building a specialist brand that needs one clear communication system?" body="I create connected identity, content, and multimedia systems across the touchpoints where a brand needs to communicate." />
  </article></main>;
}
